### ISSUE TITLE
rclone 1.34 compatibility

### ISSUE THREAD

**Issue by pigmonkey** [DanielDent/git-annex-remote-rclone#14]
rclone 1.34 was released 11 days ago. It landed in the Arch Linux repositories today. Has anyone checked to see if there are any issues with git-annex-remote-rclone?

I have not performed any tests myself yet.

**Comment by DanielDent** [comment]
I've been quite busy and haven't had a chance to look at the changes, but the test suite is still passing:  https://gitlab.com/DanielDent/git-annex-remote-rclone/builds/6335305

**Comment by pigmonkey** [comment]
I've been using 1.34 for a couple days now and everything seems peachy with my hubic, google drive, and b2 remotes.

**Comment by DanielDent** [comment]
1.34 also includes some improvements (ncw/rclone#769) which can have a huge performance benefit. It's now the recommended version.
