### ISSUE TITLE
Parallel uploads to hubic cause irritation (probably no bug, just mentioning)

### ISSUE THREAD

**Issue by fkemmer** [DanielDent/git-annex-remote-rclone#23]
This is probably more of a good-to-know than anything even remotely serious, but I thought it might be worthwhile having it written somewhere.

Backstory: Amazon Cloud Drive was killed (#22), so I'm uploading my data to [hubiC](https://hubic.com/en/) instead. As rclone doesn't deal well with lots of small-ish chunks (#1), I used to run multiple git-annex processes in parallel across different subtrees to get optimal bandwidth utilisation:
```
bash1: git-annex copy --to acd subtree1/
bash2: git-annex copy --to acd subtree2/
```

Trying to do the same with a hubic based remote caused an error along the following lines in all ongoing tranfers:
```54%      285.0KB/s 7m30s2017/06/17 00:00:23 Failed to create file system for "hubic-annex:mypath/": failed to make remote "hubic-unenc:default/annexes/fin0qnq9us3co9jmmqffqnii2s" to wrap: error authenticating swift connection: invalid character '<' looking for beginning of value```

After quite a bit of playing around with different versions of both rclone and git-annex-remote-rclone across different devices, the only aparent reason I could find was the attempted parallelisation as everything seems to work without problems now that I'm using only a single git-annex process (at the cost of some bandwidth).

If this is way too obvious, please scold me at will :)

**Comment by pigmonkey** [comment]
Use the `--jobs`/`-J` switch. I frequently tell git-annex to copy multiple files at once to a hubic remote and have never experienced errors.

    $ git-annex copy --to hubic -J4 --fast

**Comment by fkemmer** [comment]
Thanks for the heads-up. I just realised that this particular server is still running git-annex from Debian stable (not even backports) and thus doesn't understand the switch (which, if memory serves me well, was the reason for my obscure idea in the first place)

Anyway, all the more reason to just forget about this post ;) Also, while lack of parallel transfers might have had an impact with ACD, hubic is just slow either way (In my scenario, the average speeds drop from 6Mbps to 5.5 Mbps).
