### ISSUE TITLE
[Enhancement] globbered output with grep results

### ISSUE THREAD

**Issue by ANaumann85** [DanielDent/git-annex-remote-rclone#37]
If one adds a new file, git annex first checks if the file already exists on the remote.

In that case, the users sees several lines "error listing: directory not found". From a users point of view, it is not clear where that message comes from and if it might represent an error.

Please note, that there is already a [pull request](https://github.com/DanielDent/git-annex-remote-rclone/pull/31), which removes the weird output.

**Comment by DanielDent** [comment]
Thank you for mentioning the use case where this could mater. The reason I've not merged it is because I've not yet spent the time to look more carefully and consider if there might be useful errors that would also be silenced by making that change.

**Comment by ANaumann85** [comment]
yes, I also struggled a bit with this simple patch. It has the disadvantage, that you loose the information, when rclone changes the output again.

I do not understand the full details with the configuration settings. But I have two possibilities in mind:
1. Recent rclone  versions provide a json output. That might be more stable than parsing the user strings. But I have no experience with the json utilities. And using python at this point looks too expensive.
2. introduce an additional configuration option "quiet". If quiet is true, we do not print the result of the grep calls. Otherwise we print them to stderr.

**Comment by kirelagin** [comment]
I don’t quite see how discarding _stdout_ from grep can silence useful errors. Grep’s stdout only contains the matches, so it absolutely 100% does not contain anything useful.
