### ISSUE TITLE
syncing not working with rclone v1.30

### ISSUE THREAD

**Issue by donm** [DanielDent/git-annex-remote-rclone#5]
Thanks for writing this!  This is exciting.

It seems that the update to rclone version 1.30 breaks git-annex-remote-rclone because the output of `rclone size [path]` has changed when the directory does not exist.  With rclone v1.29 the output is

```
> rclone size gdrive:test-annex/non/existing
2016/06/22 02:38:21 Google drive root 'test-annex/non/existing': Couldn't find root: Couldn't find directory: "test-annex/non"
Total objects: 0
Total size: 0 (0 bytes)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:        4.9s
```

Whereas with rclone v1.30 the output is

```
> rclone size gdrive:test-annex/non/existing
2016/06/22 02:38:39 directory not found
> # and that's it
```

which git-annex-remote-rclone interprets as the remote not being found.

**Comment by DanielDent** [comment]
I am glad you find this useful :). The git-annex test suite passes with the changes I've made in version 0.3. Please let me know if you run into any additional issues.
