### ISSUE TITLE
v0.7 release

### ISSUE THREAD

**Issue by yarikoptic** [DanielDent/git-annex-remote-rclone#55]
- needed for conda-forge feedstock (#36)
- requested for getting fixes into brew distribution (#54)

Dear @DanielDent can you cut a release or want to entrust me on that (I assume it is simply just minting a github release right here in web UI, which I never did since I prefer to mint them from proper annotated tags)? ;)

**Comment by yarikoptic** [comment]
I will cut one in github releases over weekend unless I am stopped.

**Comment by DanielDent** [comment]
Yes, I actually found myself wondering the other day if I should cut a new release. Please feel free to do so with either approach.. I think I've been doing it in the web UI, but a proper annotated tag is great.

**Comment by yarikoptic** [comment]
we have it! https://github.com/DanielDent/git-annex-remote-rclone/releases/tag/v0.7
