### ISSUE TITLE
rclone 1.33 compatibility

### ISSUE THREAD

**Issue by pigmonkey** [DanielDent/git-annex-remote-rclone#7]
The README says that this has only been tested with rclone up to 1.32 and that future upgrades may break. I just thought I'd mention that I recently upgraded to the newly released rclone 1.33 and my special remotes are still working fine.

**Comment by DanielDent** [comment]
Thanks for the report. Testing revealed one issue which has been fixed in version 0.4.

**Comment by DanielDent** [comment]
I saw your posting on http://pig-monkey.com/2016/08/rclone/ - it's great to see happy users.

rclone upstream still has open issues for single-file handling. The performance concern is that a 'copy' command to upload an object will first list exist objects. It's possible that your use of the 'lower' layout is avoiding the issue. On Hubic, I suspect the 'nodir' layout would be quite slow for you - if you had many files on the remote.

If you don't mind my asking, how many objects do you have stored on Hubic, and how is the performance?

**Comment by pigmonkey** [comment]
I'm not using Hubic on my annex with a ridiciously large number of keys (150573) or my annex with a ridiciously large size (4.2 TB). I think this is the biggest Hubic annex in terms of size:

```
$ git annex info hubic
remote: hubic
description: [hubic]
uuid: c43a35b0-03e4-4225-9be2-417146922719
trust: semitrusted
cost: 550.0
type: external
externaltype: rclone
encryption: shared (encryption key stored in git repository)
chunking: 52.43 megabyteschunks
remote annex keys: 1196
remote annex size: 4.3 gigabytes
```

And this is the biggest in terms of keys:

```
$ git annex info
remote: hubic
description: [hubic]
uuid: 18ea8bed-d2c5-48fc-9911-1b02a79aa004
trust: semitrusted
cost: 550.0
type: external
externaltype: rclone
encryption: shared (encryption key stored in git repository)
chunking: 52.43 megabyteschunks
remote annex keys: 1721
remote annex size: 687.39 megabytes
```

I get poor transfer speed on hubic, but I don't feel like I'm getting hit with a long wait prior to copy.

```
$ echo 'hi' > testfile
$ git annex add testfile
add testfile ok
(recording state in git...)
$ time git annex copy testfile --to hubic
copy testfile Total objects: 0 Total size: 0 Bytes (0 Bytes) 2016/08/26 15:27:43 Transferred: 0 Bytes (0 Bytes/s) Errors: 0 Checks: 0 Transferred: 0 Elapsed time: 5.5s
(to hubic...)
0%            0.0 B/s 0s2016/08/26 15:27:49 Hubic Swift container annex-documents path 1c6/e6d/: Waiting for checks to finish
2016/08/26 15:27:49 Hubic Swift container annex-documents path 1c6/e6d/: Waiting for transfers to finish
2016/08/26 15:28:04
Transferred:     73 Bytes (3 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:       20.7s
ok
(recording state in git...)

real    0m26.576s
user    0m0.493s
sys     0m0.080s
```

The annexes that I'm using with Hubic are monitored with the Assistant, so in practice I never really see the transfers.

**Comment by pigmonkey** [comment]
Is the concern specific to Hubic?

I am actually planning to push that annex with 150k keys out to Google Drive via rclone, so that could be a good test of this issue.

**Comment by DanielDent** [comment]
The concern I'm wondering about is especially an issue on Hubic. With ~1k keys I think any layout will be fine and the problem wouldn't show up. A long wait prior to copy is precisely the issue I am worried about.

What I'm unclear is if a directory based layout (as opposed to 'nodir' which is how https://github.com/Schnouki/git-annex-remote-hubic stores data) mitigates the issue (by only listing entries in the current 'directory', not that object-based systems like Swift/Hubic really work with directories).

The 'lower' layout with 150k entries on Google Drive shouldn't have any issues.
