### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by aragilar** [DanielDent/git-annex-remote-rclone#73]
Can there be a new release, and can it get uploaded to Debian (as per https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031425)? It seems the current release does not work sometimes with Office365 OneDrive, and is unable to parse the size output.

Thanks!

**Comment by yarikoptic** [comment]
oh, we should!  and sad that we have not automated releasing process yet... I will check if all is good for my own greedy usecase and see into tagging / releasing v0.8

**Comment by yarikoptic** [comment]
there is https://github.com/git-annex-remote-rclone/git-annex-remote-rclone/releases/tag/v0.8 now.  I will look into updating debian package now
