### ISSUE TITLE
[Question] How am I supposed to set the second device?

### ISSUE THREAD

**Issue by ollieluvic** [DanielDent/git-annex-remote-rclone#74]
I've followed the same instructions on a second device, using the same rclone settings, however the second device, or even a second folder on the same device, does not get the git history nor the files. I've run sync on both devices and have verified that the files from the first got uploaded to Google Drive, but the second device seems to be unable to get any piece of information from the remote.

**Comment by yarikoptic** [comment]
Not enough context is provided - how did you share git repo to the second device? This remote only provides storage for annexed content, git repo itself you need to share independently, eg via GitHub

**Comment by ollieluvic** [comment]
@yarikoptic Thanks for the response, I'll set a regular git repo then as I have not done it before. 

I had not set a regular git repo, only the annex one, so that what is missing. For git annex itself I had followed the Assistant tutorial video on their web site and skimmed through the cli guide, from which I couldn't find any guidance on it — Maybe I searched using the wrong keywords, IDK..

**Comment by yarikoptic** [comment]
well, if you like a "book to read", then although not directly on git/git-annex but consider https://handbook.datalad.org/en/latest/ which might be a little more detailed description of many aspects of how git/git-annex work undeneath datalad ;-)
