### ISSUE TITLE
Unable to drop files from a remote

### ISSUE THREAD

**Issue by montag451** [DanielDent/git-annex-remote-rclone#8]
When I try to drop files from a remote, it doesn't work. Looking at the code, I see that you use "rclone purge" to remove file from a remote, I think you should use "rclone delete" because "rclone purge" only works on "directory".

**Comment by montag451** [comment]
The failure with "purge" happens only with rclone 1.33. I think the behaviour of "purge" in the new version of rclone is correct because now the command refuse to remove files, it accepts only directories. With the old versions of rclone, you can use "purge" on a file but it remove also the directory containing the file.

**Comment by DanielDent** [comment]
Thanks for the report. I believe version 0.4 should address issues with rclone 1.33. If you run into any further problems, please feel free to re-open this issue or file a new issue.

**Comment by DanielDent** [comment]
@montag451 I just read more closely what you said. Are you saying that "rclone purge" on older versions would delete a parent directory even if other files existed in that directory? If so, please let me know, because that would mean older git-annex-remote-rclone versions may be unsafe to use.

**Comment by montag451** [comment]
Yes. For example, say that you have a directory "foo" on a remote with 2 files inside it (say "bar" and "baz"). If you type the following command:

``` shell
rclone purge remote:foo/bar
```

with previous version of rclone, it will delete "bar", "baz" and the directory "foo". So I think previous version of git-annex-remote-rclone are unsafe since dropping one file could in fact drop several files.

**Comment by DanielDent** [comment]
That's extremely troubling. Thank you for the report.

**Comment by montag451** [comment]
You are welcome!

**Comment by DanielDent** [comment]
Added a warning in README.md in 3c2b84bc73bd79d4d7016dbcd71b177513cfaae9
